### ISSUE TITLE
How to find the co ordinates of long reads with respect to the reference genome from which the reads were simulated

### ISSUE THREAD

**Issue by Oieswarya** [rrwick/Badread#18]
I have simulated a set of ONT long reads (10x) of E coli using the Badreads simulator tool. I was wondering is there any way I can know the co ordinates (positions) of these long reads in the reference genome from where they were simulated. I know most simulators have some metadata attached to the files that they are generating, but I could not find any thing like that in the Badreads file.

**Comment by rrwick** [comment]
This information should be in the FASTQ headers. For example, this read:
```
@6fdc99eb-c3fb-3c9d-2915-660f302289e9 chromosome,+strand,860569-877496 length=16827 error-free_length=16933 read_identity=95.53%
```
 contains the following info:
* read name: `6fdc99eb-c3fb-3c9d-2915-660f302289e9`
* contig, strand and position in reference genome: `chromosome,+strand,860569-877496`
* actual length of read: `length=16827`
* length of read before adapters/errors were added: `error-free_length=16933`
* identity of the read: `read_identity=95.53%`
