### ISSUE TITLE
Are complementary sequences simulated.

### ISSUE THREAD

**Issue by RDorney** [rrwick/Badread#23]
Hello,
I have a question regarding the methodology of Badread.
I've noticed that the fastq headers will include -/+ strand information. Does BadRead also simulate the complementary sequence to the inputted fasta sequence?
I'm attempting to simulate transcriptomic reads and worry this may be problematic for what I'm interested in doing, so would like to check before I proceed to search for a different simulator to use

**Comment by rrwick** [comment]
Yes, Badread produces reads from both strands, chosen at random:
https://github.com/rrwick/Badread/blob/09fb3082e5b2530c4e17e20e262ff227eb28ff13/badread/simulate.py#L191-L196

While there's no way to change this when running Badread, you can filter the resulting reads using some Bash, for example:
```bash
cat badread.fastq | paste - - - - | grep -v ",-strand" | tr '\t' '\n' > pos_strand_only.fastq
```

This should result in a read set about half the size with only positive strand reads.

**Comment by RDorney** [comment]
could this be rectified by changing 
https://github.com/rrwick/Badread/blob/fc1bd9821df478e981c614d21b775d75fc9636ab/badread/simulate.py#L38
to in my case to
```
    rev_comp_ref_seqs = ref_seqs
```
