### ISSUE TITLE
How to simulate Pacbio hifi reads?

### ISSUE THREAD

**Issue by JianjunJin** [rrwick/Badread#24]
**Is your feature request related to a problem? Please describe.**
I wonder how we can simulate Pacbio hifi reads using `Badread`. Do the `very good reads` described in the [Quick Usage](https://github.com/rrwick/Badread#quick-usage) mean Pacbio hifi reads?

**Describe the solution you'd like**
Parameters for `Badread`.

Thanks for providing this nice tool!

**Comment by rrwick** [comment]
I don't have a lot of experience with PacBio HiFi reads, but off the top of my head, here's a command you can use:
```
badread simulate --reference ref.fasta --quantity 50x --identity 30,3 --length 25000,3000 --junk_reads 0 --random_reads 0 --glitches 0,0,0 --start_adapter_seq "" --end_adapter_seq "" | gzip > reads.fastq.gz
```
* `--identity 30,3` sets the read identity to be high, with a median accuracy of 99.9%.
* `--length 25000,3000` set a tight length distribution around 25 kbp.
* `--junk_reads 0 --random_reads 0 --glitches 0,0,0 --start_adapter_seq "" --end_adapter_seq ""` disables junk reads, random reads, glitches and adapters.

I don't know what the typical chimera rates are in PacBio HiFi reads, so I've left that at Badread's default (1%).

Also note that this command uses Badread's default [error model](https://github.com/rrwick/Badread/wiki/Error-models) and [qscore model](https://github.com/rrwick/Badread/wiki/QScore-models), which were trained on modern Nanopore reads. So if you really wanted to simulated HiFi reads well, you should probably [train your own error and qscore models](https://github.com/rrwick/Badread/wiki/Generating-error-and-qscore-models) using HiFi reads.

Hope that helps!
Ryan

**Comment by JianjunJin** [comment]
Thank you so much, Ryan!
Jianjun
