### ISSUE TITLE
Error models and te technology of real reads

### ISSUE THREAD

**Issue by jyw-atgithub** [rrwick/Badread#27]
Hi @rrwick ,

The documentation describes several error models and quality models.  May I know the corresponding technology of each model?  For example, 

|model name|tech|
|---|---|
|nanopore2023 | Minion, R10.4.1 flow cell and Kit 14 ?|
|pacbio2016|Pacbio RS II ?? Sequel II ??|

 Thank you!

**Comment by HLHsieh** [comment]
Hi, I would like to follow up on this question as well!
