### ISSUE TITLE
Do q-scores adhere to phred33?

### ISSUE THREAD

**Issue by JonathanAbrahams1337** [rrwick/Badread#30]
Hi,

A little lost when looking through the simulated fastq data. 

There appears to be characters in the quality score which aren't described in phred 32, such as "{".

[example read.txt](https://github.com/rrwick/Badread/files/14601246/example.read.txt)

This was simulated using latest 2023 ONT model.

I notice in this file that each cigar string is associated with 90+ comma delimited fields and , if I am reading the Badread documentation correctly, this would be associated with 90 different ASCII characters.

The 2018 simulated dataset and the examples in the documentation have 29 fields, but 2020 and 2023 have more.

Interested to hear more about this, 

Jonathan

**Comment by rrwick** [comment]
Hi Jonathan,

Badread does use Phred+33 ([see the code here](https://github.com/rrwick/Badread/blob/main/badread/qscore_model.py#L321-L326)). And yes, `{` does mean a qscore of 90 which equates to a 0.0000001% of an error. I agree that this is ridiculous, but I checked, and the real Nanopore reads I used to build the `nanopore2023` model do in fact contain `{` characters in their qscores.

However, I then checked some of my latest Nanopore reads (using the most recent [Dorado basecalling models](https://github.com/nanoporetech/dorado#dna-models)), and they _don't_ contain `{` characters. So clearly the qscores can depend on the basecaller/model and change a lot from version to version.

Ryan
