### ISSUE TITLE
Positions in the read header line are incorrect for all sequences from - strand.

### ISSUE THREAD

**Issue by shenwei356** [rrwick/Badread#34]
Hi Ryan @rrwick , I found a small bug here.

**Describe the bug**

Positions in the read header line are incorrect if the sequence comes **from - strand**, a few from + strand are also not right.

**To reproduce**

Badread version: v0.4.1 [fc1bd98](https://github.com/rrwick/Badread/commit/fc1bd9821df478e981c614d21b775d75fc9636ab), installed by 

```
git clone https://github.com/rrwick/Badread.git
pip3 install ./Badread
```

Genome:  [GCF_000005845.2.fna.gz](https://github.com/user-attachments/files/15915654/GCF_000005845.2.fna.gz)

```
$ seqkit stats GCF_000005845.2.fna.gz 
file                    format  type  num_seqs    sum_len    min_len    avg_len    max_len
GCF_000005845.2.fna.gz  FASTA   DNA          1  4,641,652  4,641,652  4,641,652  4,641,652
```

```
# generate some reads without any error
badread simulate --seed 1 --reference GCF_000005845.2.fna.gz \
                    --quantity 1x --length 1000,0 \
                    --identity 100,100,0 \
                    --error_model random --qscore_model ideal \
                    --glitches 0,0,0 --junk_reads 0 --random_reads 0 --chimeras 0 \
                    --start_adapter_seq "" --end_adapter_seq "" \
     > reads.fq

# mapping back with seqkit, as they are error-free reads. https://github.com/shenwei356/seqkit
seqkit locate -f <(seqkit head -n 100 reads.fq) GCF_000005845.2.fna.gz  -o 100.tsv -M

# checking positions, csvtk is used. https://github.com/shenwei356/csvtk.
# a position record is wrong if the end is not right.
# badread use a BED-like position: 0-based [start, end) .
cat 100.tsv \
    | csvtk cut -t -f -pattern \
    | csvtk mutate -t -f 2 -p 'strand,(\d+)\-' -n bstart \
    | csvtk mutate -t -f 2 -p 'strand,\d+\-(\d+)' -n bend \
    | csvtk filter2 -t -f '$end != $bend ' \
    | tee 100.tsv.bad \
    | csvtk cut -t -f -patternName \
    | csvtk freq -t -f strand -k
strand  frequency
+       5
-       54

# all records
csvtk freq -t -f strand -k 100.tsv
strand  frequency
+       55
-       54

```

Some bad position: (I don't see any pattern).

|seqID      |patternName                                                                                                                       |strand|start  |end    |bstart |bend   |
|:----------|:---------------------------------------------------------------------------------------------------------------------------------|:-----|:------|:------|:------|:------|
|NC_000913.3|923215ed-8821-59b1-69ce-0be2166944e8 NC_000913.3,-strand,2356744-2357744 length=1000 error-free_length=1000 read_identity=100.000%|-     |2283909|2284908|2356744|2357744|
|NC_000913.3|7e14f067-9c6a-1a09-697a-73be05c3defb NC_000913.3,-strand,3851731-3852731 length=1000 error-free_length=1000 read_identity=100.000%|-     |788922 |789921 |3851731|3852731|
|NC_000913.3|f0b3c10c-b1e6-a3d4-0cf3-bd0abae649de NC_000913.3,-strand,2004162-2005162 length=1000 error-free_length=1000 read_identity=100.000%|-     |2636491|2637490|2004162|2005162|
|NC_000913.3|08fbc4a1-dfef-4238-50a4-c69f19ad1927 NC_000913.3,-strand,990508-991508 length=1000 error-free_length=1000 read_identity=100.000%  |-     |3650145|3651144|990508 |991508 |

Also excluded cases of duplicated regions.

```
# https://github.com/shenwei356/wfa
wfa-go $(seqkit subseq GCF_000005845.2.fna.gz -r 2283909:2284908 | seqkit seq -s) \
       $(seqkit subseq GCF_000005845.2.fna.gz -r 2356745:2357744 | seqkit seq -s)
match-region: q[3, 998]/1000 vs t[3, 998]/1000
align-length: 1105, matches: 517 (46.79%), gaps: 218, gap regions: 63
```

**Error message**
No

**System info**
 - OS: Manjaro
 - Python version 3.9.18

**Additional context**

**Comment by rrwick** [comment]
Thanks for the thorough instructions to reproduce your results!

For negative strand reads, Badread is reporting the position in terms of the negative strand, not in terms of the positive strand.

Using the `923215ed` read as an example, here are the two alternative ways to get the read's location:
* Take the reverse-complement of the `GCF_000005845.2` sequence, and look at positions 2356744-2357744 (what Badread reported), and you'll find that read's sequence.
* From the the `GCF_000005845.2` sequence, extract positions 2283908-2284908 (what seqkit gave), then take the reverse complement to find that read's sequence.

The hidden pattern in the results is therefore this: end + bstart = 4641652 (the sequence length)

Sorry if that's counterintuitive!

And regarding the few positive-strand reads which mismatch, I think this is when reads are in repeat regions and have multiple locations. When I manually checked these, they looked good to me. So I think the issue there is somewhere in your big csvtk one-liner.

Hope that helps! Let me know if I can clarify anything further.

Ryan

**Comment by shenwei356** [comment]
> For negative strand reads, Badread is reporting the position in terms of the negative strand, not in terms of the positive strand.

Got it. Maybe you can consider using positions on the positive strand in future versions.

> And regarding the few positive-strand reads which mismatch, I think this is when reads are in repeat regions and have multiple locations.

Checked it again, you're right.

Ryan, thanks for your explanation.
