### ISSUE TITLE
Confusion about total base sizes 

### ISSUE THREAD

**Issue by kuyilmaz** [rrwick/Badread#35]
Hello,

Thank you for generating this tool. I'm trying to simulate nanopore reads (R9.4.1). When I check the real data I have with FastQC, one FASTQ file contains 140 Gbp, which is quite large. Parallelization also requires a lot of memory, making the process even more challenging.

Do you have any suggestions? Am I missing something?

Thanks a lot,
Kübra

**Comment by rrwick** [comment]
Hi Kübra,

I assume this is for a larger eukaryotic genome or a metagenome? If so, then 140 GB sounds plausible. So no, I don't think you're missing anything. Being a Python-based tool, Badread is not super fast.

I haven't tried it myself, but I recall this tool which was a Rust-based reimplementation of Badread: https://github.com/natir/rustyread
You could give that a try and see how much faster it is.

Ryan

**Comment by kuyilmaz** [comment]
Hi Ryan,

Thanks a lot. Yes, I'm trying to simulate whole human genome nanopore
reads. I'll check the rustyread!

Sincerely,
Kübra

Ryan Wick ***@***.***>, 19 Ağu 2024 Pzt, 05:06 tarihinde şunu
yazdı:
