### ISSUE TITLE
pi3 install ./Badread fails with "'ascii' codec can't decode byte 0xe2" error

### ISSUE THREAD

**Issue by rcedgar** [rrwick/Badread#9]
O/S:  Ubuntu 18.04.4
Python: v3.6.9

After successful git clone, this command:

pip3 install ./Badread

Fails for me as follows:

Cloning into 'Badread'...
badread --helpremote: Enumerating objects: 26, done.
remote: Counting objects: 100% (26/26), done.
remote: Compressing objects: 100% (17/17), done.
remote: Total 800 (delta 13), reused 18 (delta 9), pack-reused 774
Receiving objects: 100% (800/800), 20.37 MiB | 6.53 MiB/s, done.
Resolving deltas: 100% (496/496), done.
[bob@gig] /media/bob/Elements/sw/badread> pip3 install ./Badread
Processing ./Badread
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-230bkixz-build/setup.py", line 76, in <module>
        long_description=readme(),
      File "/tmp/pip-230bkixz-build/setup.py", line 28, in readme
        return f.read()
      File "/usr/lib/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 126: ordinal not in range(128)

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-230bkixz-build/

**Comment by rrwick** [comment]
I think I've fixed this one now! The problem seems to be that the README is encoded in UTF-8, but for some reason your system defaulted to ASCII. I've now explicitly set UTF-8 as the encoding for that file. Thanks!
